[package]
name = "fourier-prof"
version = "0.1.0"
authors = ["Caleb Zulawski <caleb.zulawski@gmail.com>"]
edition = "2018"

[dependencies]
clap = "2.33"
fourier = { path = "../fourier" }
rand = "0.7"
num-complex = "0.2"

[profile.release]
debug = true
panic = "abort"
