name: C/C++

on: [push]

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: Configure
      run: cmake -S fourier-ffi -B build -G "Unix Makefiles"
    - name: Build
      run: make -C build
    - name: Test
      run: make -C build test
